test_ratio: 0.3
automl_max_evals: 10
gcp_project_id: "purchasepredict-454010"
gcs_primary_folder: "purchasepredict/output.csv"
mlflow_enabled: True # Do we log metrics and artifacts to MLflow ?
mlflow_experiment_id: 1 # Experimented ID associated to this project
mlflow_model_registry: "purchase_predict" # Name of model registry of this project